### ISSUE TITLE
Feat: Add Dependabot for flutter dependency Updates

### ISSUE THREAD

**Issue by prajapatihet** [avinashkranjan/logsuite#11]
**Describe the feature**

I propose integrating Dependabot into our project to automate dependency updates. Dependabot will regularly check for updates, ensuring we stay current with the latest features and security patches. This will save time, enhance security, and maintain consistency in our development process.

 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by prajapatihet** [comment]
Assign this issue to me @avinashkranjan

**Comment by avinashkranjan** [comment]
I don't need `Dependabot` in the repository,
