### ISSUE TITLE
Figma design Landing page

### ISSUE THREAD

**Issue by Rohitha-pudu** [avinashkranjan/logsuite#22]
i will design the landing page in figma

**Comment by avinashkranjan** [comment]
Go Ahead @Rohitha-pudu

**Comment by avinashkranjan** [comment]
Hey @Rohitha-pudu , Update the design https://dribbble.com/shots/17533112-AppBuilder-Landing-Page/attachments/12675279?mode=media , Like this, So, It should have 

- Hero Section
- Info Section
- Why Section
- Pricing Section
- Contact Section
- Header & Footer

**Comment by avinashkranjan** [comment]
Theme looks good, Just make it in light and dark theme, that's all @Rohitha-pudu , Either that or split this into two issues for light and dark mode.

**Comment by Rohitha-pudu** [comment]
> Theme looks good, Just make it in light and dark theme, that's all @Rohitha-pudu , Either that or split this into two issues for light and dark mode.

i have added sections can u check if they are ok @avinashkranjan

**Comment by Rohitha-pudu** [comment]
> Theme looks good, Just make it in light and dark theme, that's all @Rohitha-pudu , Either that or split this into two issues for light and dark mode.

in that case can i get level 3 ,as this is more to do ,adding sections and theme

**Comment by avinashkranjan** [comment]
LGTM.. Create a PR for the same on `website` branch
