### ISSUE TITLE
Screenshot Capture

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/logsuite#3]
# Objective
Capture screenshots every 100ms and save them to device storage without taking permission. Reference UxCam/UserExperior for implementation.

# Requirements

- Implement a mechanism to capture screenshots every 100ms.
- Save the captured screenshots to device storage.
- Ensure the process does not require explicit permission from the user.

# Steps to Implement

1. Create a ScreenshotCapture class.
2. Use a timer to trigger screenshot capture every 100ms.
3. Save the screenshots to a predefined directory on the device.
4. Ensure the functionality works on both Android and iOS.

# Resources
[Screenshot package](https://pub.dev/packages/screenshot)

**Comment by Saumya-28** [comment]
Hi @avinashkranjan !
I would like to work on this issue. Could you please specify more about this issue? Do we have to create a separate application implementing this logsuite plugin or just a dart class?

**Comment by avinashkranjan** [comment]
Sure @Saumya-28 Go Ahead, While submiting the PR, attach a working video demo as well.
