### ISSUE TITLE
Automatic copyright.

### ISSUE THREAD

**Issue by tarushi29** [avinashkranjan/logsuite#31]
The code contains manual copyright which needs to be changed every year manually.
I can add a automatic copyright code which reduces manual effort to update every year.

![image](https://github.com/avinashkranjan/logsuite/assets/128239884/a44fcdc0-01f4-4d8d-8850-3edcb92dec77)

**Comment by avinashkranjan** [comment]
Go Ahead @tarushi29

**Comment by tarushi29** [comment]
please assign it to someone else i m into react js not flutter sorry
