### ISSUE TITLE
DOC: README File Modification for Better Attractiveness and Understandability

### ISSUE THREAD

**Issue by piyushsahujtp** [avinashkranjan/logsuite#38]
### What's wrong with the existing documentation

The current README file for the project requires modifications to make it more attractive and easier to understand. The aim is to ensure that new users can quickly grasp the purpose of the project, how to set it up, and how to contribute. Below are the specific improvements needed.

### Add Screenshots

![Screenshot 2024-06-25 135713](https://github.com/avinashkranjan/logsuite/assets/111915697/e640c418-2f79-4d09-b72a-6f3107cc809b)

Expected Outcome:
A well-structured, visually appealing, and informative README file that enhances user engagement and facilitates easier understanding of the project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GirlScript Summer of Code 2024 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @piyushsahujtp

**Comment by Bliss011** [comment]
Can i do this task. Please assign it to me @avinashkranjan

**Comment by avinashkranjan** [comment]
We already have a standing PR for the same @Bliss011
