### ISSUE TITLE
Crash Log Recording

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/logsuite#4]
# Objective
Automatically capture and record crash logs with relevant information when a crash occurs. Save crash logs to device storage and provide an API for retrieval.

# Requirements

- Automatically capture crash logs with relevant information.
- Save the crash logs to device storage.
- Provide an API to retrieve the crash logs.

# Steps to Implement

1. Create a CrashLogRecorder class.
2. Use a package like catcher to automatically capture crash logs.
3. Save the captured logs to a predefined directory on the device.
4. Implement an API to retrieve the crash logs.

# Resources
[Catcher package](https://pub.dev/packages/catcher)
[Device Info Plus package](https://pub.dev/packages/device_info_plus)

**Comment by Asymtode712** [comment]
@avinashkranjan please assign me this issue

**Comment by avinashkranjan** [comment]
@Asymtode712 Go Ahead, Assigned to you, Submit a working video when you create the PR..
