### ISSUE TITLE
Export Logs to Different Formats:

### ISSUE THREAD

**Issue by sanskriti-lal** [avinashkranjan/logsuite#42]
**Is your feature request related to a problem? Please describe.**
It is usually frustrating to manually copy logs and convert to different formats for analysis or sharing, which is time-consuming and prone to errors. Having an integrated export feature for logs in various formats like JSON, CSV, and plain text would greatly enhance usability and streamline the process for developers.

**Describe the solution you'd like**
I would like LogSuite to include an option to export logs directly from the application in various formats, such as JSON, CSV, and plain text. This feature should allow developers to select the desired format and easily save the logs to a file, making it more convenient to share and analyze logs without manual conversion.

**Describe alternatives you've considered**
Using third-party logging libraries that already support multiple export formats, but this would require integrating and managing additional dependencies, potentially complicating the project.

**Additional context**
I'm a GSSoC'24 contributor and I want to work on this. So can you please assign it to me @avinashkranjan

**Comment by avinashkranjan** [comment]
Go Ahead @sanskriti-lal
