### ISSUE TITLE
Make Scrollbar stylish

### ISSUE THREAD

**Issue by zalabhavy** [avinashkranjan/logsuite#43]
**Is your feature request related to a problem? Please describe.**
I will add stylish scrollbar in this website.

**Describe the solution you'd like**
![image](https://github.com/avinashkranjan/logsuite/assets/126322584/e96b09e5-c65a-470b-bc14-053ea15f8ebc)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by zalabhavy** [comment]
@avinashkranjan Please assign me this task !

**Comment by avinashkranjan** [comment]
Not Needed, and not in the scope of the project..
