### ISSUE TITLE
Network Log Capture

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/logsuite#5]
# Objective
Intercept and log all network requests and responses. Save network logs to device storage and expose an API for retrieval.

# Requirements

- Intercept all network requests and responses.
- Log the intercepted data.
- Save the logs to device storage.
- Provide an API to retrieve the network logs.

# Steps to Implement

1. Create a NetworkLogCapture class.
2. Use a package like http or dio to intercept network requests and responses.
3. Log the intercepted data.
4. Save the logs to a predefined directory on the device.
5. Implement an API to retrieve the network logs.

# Resources
[Http package](https://pub.dev/packages/http)
[Dio package](https://pub.dev/packages/dio)

**Comment by Saumya-28** [comment]
Hi @avinashkranjan !
I would like to work on this issue. Could you please assign it to me?

**Comment by avinashkranjan** [comment]
Go Ahead @Saumya-28
