### ISSUE TITLE
Sample Application

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/logsuite#6]
# Objective
Develop a sample Flutter application that demonstrates the integration and usage of the plugin. The sample application should showcase the plugin's functionality, including screenshot capture, crash log recording, and network log capture. Provide clear instructions on how to run the sample application and observe the plugin's behavior.

# Requirements

- Develop a sample Flutter application.
- Integrate the `flutter_log_capture` plugin.
- Demonstrate screenshot capture functionality.
- Demonstrate crash log recording functionality.
- Demonstrate network log capture functionality.
- Provide clear instructions on how to run the sample application.
- Steps to Implement

# Create a new Flutter application.

1. Add the `flutter_log_capture` plugin as a dependency.
2. Implement the UI to demonstrate screenshot capture.
3. Implement the UI to demonstrate crash log recording.
4. Implement the UI to demonstrate network log capture.
5. Write instructions on how to run the sample application.

**Comment by Manikasethi** [comment]
Hey please assign this issue to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Manikasethi

**Comment by Manikasethi** [comment]
can you please share the link for this library

**Comment by avinashkranjan** [comment]
This is the library only @Manikasethi..

**Comment by Manikasethi** [comment]
Ik but I'm Unable to find it on pub dev 
I guess this is discontinued or something 
If you have the link please share

**Comment by avinashkranjan** [comment]
This hasn't been uploaded, as it is still in development.

**Comment by Manikasethi** [comment]
Okay, Thankyou
